version: "3.7"
networks:
    webapp:
services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    restart: always
    ports:
      - 8090:80
    networks:
      - webapp


  kinstondb: 
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 2180129
      POSTGRES_USER: uriel
      POSTGRES_DB: kinstonm
    ports:
      - "5432:5432"
    networks:
      - webapp
    volumes:
      - pgdata:/var/lib/postgresql/data



volumes:
  pgdata:
  